name: Python Code Style and Quality Check

on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Check code with Pylint
        run: |
          files=$(find . -name '*.py')
          if [ -n "$files" ]; then
            echo "Running Pylint..."
            echo "$files" | xargs pylint
          else
            echo "No Python files to lint."
          fi
